### ISSUE TITLE
After introducing cross-building there is bug with resolving Graph/submit.

### ISSUE THREAD

**Issue by lwronski** [ckipp01/mill-github-dependency-graph#96]
After updating the `mill-github-dependency-graph` to version `0.2.3` in the scala-cli repository, it is now throwing an error [error](https://github.com/VirtusLab/scala-cli/actions/runs/5109822211/jobs/9185025628#step:5:60):

```
Cannot resolve io.kipp.mill.github.dependency.graph.Graph.submit. Try `mill resolve io.kipp.mill.github.dependency.graph.Graph._` to see what's available.
[60](https://github.com/VirtusLab/scala-cli/actions/runs/5109822211/jobs/9185025628#step:5:61)
Error: Error: The process '/home/runner/work/scala-cli/scala-cli/mill' failed with exit code 1
```

I suppose that it is issue after introducing cross-building into `mill-github-dependency-graph`.

**Comment by ckipp01** [comment]
Thanks for reporting @lwronski! I should have this fixed in #97 and released shortly.
